2024-02-08T22:59:42 {"cpu": 0.02685546875, "cpu_total": 12, "cpu_usage": 0.0022379557291666665, "memory": 977.0, "memory_total": 8864.0, "memory_usage": 0.110221119133574, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "2156a6b6cd4d", "level": "INFO", "message": "Pipeline green_taxi_etl for run 1 in schedule 1 is alive.", "timestamp": 1707433182.988021, "uuid": "122786683313486aba33217beb488818"}
2024-02-08T22:59:43 {"block_run_id": 1, "block_uuid": "load_api_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "2156a6b6cd4d", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 1: pipeline green_taxi_etl block load_api_data", "timestamp": 1707433183.180309, "uuid": "0cc1a29fa2b847818dd649128c552f7d"}
2024-02-08T22:59:43 {"block_run_id": 4, "block_uuid": "load_taxi_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "2156a6b6cd4d", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 4: pipeline green_taxi_etl block load_taxi_data", "timestamp": 1707433183.188187, "uuid": "5ff6acbc2e584b6d8e75b76e637b0e59"}
2024-02-08T22:59:43 {"cpu": 0.02685546875, "cpu_total": 12, "cpu_usage": 0.0022379557291666665, "memory": 1149.0, "memory_total": 8864.0, "memory_usage": 0.12962545126353792, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "2156a6b6cd4d", "level": "INFO", "message": "Pipeline green_taxi_etl for run 1 in schedule 1 is alive.", "timestamp": 1707433183.193622, "uuid": "2c1653a51657421a8cb56299017f3640"}
2024-02-08T22:59:44 {"block_run_id": 5, "block_uuid": "test_gcs", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "2156a6b6cd4d", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 5: pipeline green_taxi_etl block test_gcs", "timestamp": 1707433184.190166, "uuid": "1fc54ddafd034bf9835fff3b465f8beb"}
2024-02-08T22:59:44 {"block_run_id": 5, "block_uuid": "test_gcs", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "2156a6b6cd4d", "level": "INFO", "message": "BlockRun 5 (block_uuid: test_gcs) completes.", "timestamp": 1707433184.855831, "uuid": "5fc84347e05b4a2a9680c837626815f2"}
2024-02-08T22:59:45 {"block_run_id": 1, "block_uuid": "load_api_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "2156a6b6cd4d", "level": "INFO", "message": "BlockRun 1 (block_uuid: load_api_data) completes.", "timestamp": 1707433185.195905, "uuid": "22b624a594e64ffcb1dac29e4672bb84"}
2024-02-08T22:59:46 {"block_run_id": 4, "block_uuid": "load_taxi_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "2156a6b6cd4d", "level": "INFO", "message": "BlockRun 4 (block_uuid: load_taxi_data) completes.", "timestamp": 1707433186.199456, "uuid": "90c11d66cd6747b393c8fbf26295cdf3"}
2024-02-08T22:59:52 {"cpu": 0.0322265625, "cpu_total": 12, "cpu_usage": 0.002685546875, "memory": 1121.0, "memory_total": 8864.0, "memory_usage": 0.12646660649819494, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "2156a6b6cd4d", "level": "INFO", "message": "Pipeline green_taxi_etl for run 1 in schedule 1 is alive.", "timestamp": 1707433192.3165, "uuid": "396406696ef646c09aee09a2fc75a4f6"}
2024-02-08T22:59:52 {"block_run_id": 2, "block_uuid": "transform_taxi_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "2156a6b6cd4d", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 2: pipeline green_taxi_etl block transform_taxi_data", "timestamp": 1707433192.382853, "uuid": "51c53110edf948228475249cf970e6e3"}
2024-02-08T22:59:52 {"block_run_id": 2, "block_uuid": "transform_taxi_data", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "2156a6b6cd4d", "level": "INFO", "message": "BlockRun 2 (block_uuid: transform_taxi_data) completes.", "timestamp": 1707433192.603129, "uuid": "430f7d6c9c044ff1a232abb4fcaec8c8"}
2024-02-08T23:00:02 {"cpu": 0.06982421875, "cpu_total": 12, "cpu_usage": 0.005818684895833333, "memory": 1128.0, "memory_total": 8864.0, "memory_usage": 0.1272563176895307, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "2156a6b6cd4d", "level": "INFO", "message": "Pipeline green_taxi_etl for run 1 in schedule 1 is alive.", "timestamp": 1707433202.452658, "uuid": "2dd2a412ea824d659acdc728a748a5aa"}
2024-02-08T23:00:02 {"block_run_id": 3, "block_uuid": "taxi_data_to_postgres", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "2156a6b6cd4d", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 3: pipeline green_taxi_etl block taxi_data_to_postgres", "timestamp": 1707433202.520971, "uuid": "2ac9df2062f4461596c25725db81bef9"}
2024-02-08T23:00:03 {"block_run_id": 3, "block_uuid": "taxi_data_to_postgres", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "2156a6b6cd4d", "level": "EXCEPTION", "message": "BlockRun 3 (block_uuid: taxi_data_to_postgres) failed.", "timestamp": 1707433203.00759, "uuid": "a29e7c9b261b4236a50f2bc403448bc6", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/base.py\", line 347, in conn\n    return self._ctx\nAttributeError: 'Postgres' object has no attribute '_ctx'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 613, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 588, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1077, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1312, in execute_sync\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1221, in execute_sync\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1527, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1683, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1722, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 25, in export_data_to_postgres\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py\", line 359, in export\n    __process()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py\", line 292, in __process\n    table_exists = self.table_exists(schema_name, table_name)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/postgres.py\", line 166, in table_exists\n    with self.conn.cursor() as cur:\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/io/base.py\", line 349, in conn\n    raise ConnectionError(\nConnectionError: No connection currently open. Open a new connection to access this property.\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 163, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 659, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 87, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 50, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1603, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 319, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 584, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 27, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 108, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 183, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 288, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 253, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1128, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 641, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 149, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 415, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 59, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["No connection currently open. Open a new connection to access this property."]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/base.py", line 347, in conn
    return self._ctx
AttributeError: 'Postgres' object has no attribute '_ctx'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 613, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 588, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1077, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1312, in execute_sync
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1221, in execute_sync
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1527, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1683, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1722, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 25, in export_data_to_postgres
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py", line 359, in export
    __process()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/sql.py", line 292, in __process
    table_exists = self.table_exists(schema_name, table_name)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/postgres.py", line 166, in table_exists
    with self.conn.cursor() as cur:
  File "/usr/local/lib/python3.10/site-packages/mage_ai/io/base.py", line 349, in conn
    raise ConnectionError(
ConnectionError: No connection currently open. Open a new connection to access this property.
2024-02-08T23:00:03 {"block_run_id": 6, "block_uuid": "taxi_to_gcs_parquet", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "2156a6b6cd4d", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 6: pipeline green_taxi_etl block taxi_to_gcs_parquet", "timestamp": 1707433203.567447, "uuid": "949797746de847b2a392b3b9bc060946"}
2024-02-08T23:00:03 {"block_run_id": 7, "block_uuid": "taxi_to_gcs_partitioned_parquet", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "2156a6b6cd4d", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 7: pipeline green_taxi_etl block taxi_to_gcs_partitioned_parquet", "timestamp": 1707433203.571135, "uuid": "362bd1a8c86e45808b9fdf7ecba4d9f9"}
2024-02-08T23:00:04 {"block_run_id": 6, "block_uuid": "taxi_to_gcs_parquet", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "2156a6b6cd4d", "level": "INFO", "message": "BlockRun 6 (block_uuid: taxi_to_gcs_parquet) completes.", "timestamp": 1707433204.90991, "uuid": "f6257f3b15cd443e9c51e026aed28e79"}
2024-02-08T23:00:07 {"block_run_id": 7, "block_uuid": "taxi_to_gcs_partitioned_parquet", "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "2156a6b6cd4d", "level": "INFO", "message": "BlockRun 7 (block_uuid: taxi_to_gcs_partitioned_parquet) completes.", "timestamp": 1707433207.083125, "uuid": "6cf5b556c71e4da59385f16f53eab7b4"}
2024-02-08T23:00:12 {"cpu": 0.0859375, "cpu_total": 12, "cpu_usage": 0.007161458333333333, "memory": 1135.0, "memory_total": 8864.0, "memory_usage": 0.1280460288808664, "pipeline_run_id": 1, "pipeline_schedule_id": 1, "pipeline_uuid": "green_taxi_etl", "hostname": "2156a6b6cd4d", "level": "INFO", "message": "Pipeline green_taxi_etl for run 1 in schedule 1 is alive.", "timestamp": 1707433212.613899, "uuid": "51652dd377754682bf679e3a3d2da0fa"}
